# Generated by Django 3.0.2 on 2020-08-18 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='商品')),
                ('shop', models.CharField(blank=True, max_length=256, verbose_name='店')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='価格')),
                ('count', models.IntegerField(default=1, verbose_name='個数')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='最後に買った日')),
                ('buy_date', models.DateField(default=django.utils.timezone.now, verbose_name='買う日')),
                ('past', models.IntegerField(blank=True, null=True, verbose_name='経過日数')),
                ('buy_or_not', models.BooleanField(default=False, verbose_name='購入済')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
