# Generated by Django 3.0.2 on 2020-01-20 21:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='タスク名')),
                ('deadline', models.DateField(blank=True, default=datetime.date(2020, 1, 21), null=True, verbose_name='期限')),
                ('when', models.DateField(blank=True, default=datetime.date(2020, 1, 21), verbose_name='実行予定日')),
                ('done_or_not', models.BooleanField(default=False)),
                ('done_date', models.DateField(blank=True, default=datetime.date(2020, 1, 21), null=True, verbose_name='完了した日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
