# Generated by Django 3.0.2 on 2020-01-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0002_auto_20200118_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Done',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
