# Generated by Django 3.0.2 on 2020-01-26 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0003_auto_20200125_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=True, verbose_name='重要'),
        ),
        migrations.AddField(
            model_name='task',
            name='urgent',
            field=models.BooleanField(default=True, verbose_name='緊急'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='期限'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='完了した日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='when',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='実行予定日'),
        ),
    ]
