# Generated by Django 3.0.2 on 2020-02-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0005_auto_20200126_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0, verbose_name='順番'),
        ),
    ]
