# Generated by Django 3.0.2 on 2020-01-19 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0005_auto_20200119_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Done',
        ),
        migrations.AddField(
            model_name='task',
            name='done_or_not',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='期限'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=256, verbose_name='タスク名'),
        ),
    ]
