# Generated by Django 3.0.2 on 2020-02-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0006_task_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinePush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='ユーザーID')),
            ],
        ),
    ]
