# Generated by Django 3.0.2 on 2020-01-19 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0007_auto_20200119_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='when',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='実行予定日'),
        ),
    ]
