# Generated by Django 3.0.2 on 2020-02-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0007_linepush'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinePush',
        ),
    ]
