# Generated by Django 3.0.2 on 2020-02-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0008_delete_linepush'),
    ]

    operations = [
        migrations.CreateModel(
            name='Done',
            fields=[
                ('name', models.CharField(max_length=256)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LinePush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='ユーザーID')),
            ],
        ),
    ]
