# Generated by Django 3.0.2 on 2020-01-20 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0008_task_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done_or_not',
        ),
        migrations.AddField(
            model_name='task',
            name='done_date',
            field=models.DateField(blank=True, null=True, verbose_name='完了した日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date(2020, 1, 20), null=True, verbose_name='期限'),
        ),
        migrations.AlterField(
            model_name='task',
            name='when',
            field=models.DateField(blank=True, default=datetime.date(2020, 1, 20), verbose_name='実行予定日'),
        ),
    ]
