# Generated by Django 3.0.2 on 2020-02-10 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskManager', '0010_delete_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linepush',
            old_name='user_id',
            new_name='line_id',
        ),
        migrations.AddField(
            model_name='linepush',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
