# Generated by Django 3.0.2 on 2020-01-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0010_auto_20200121_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
