# Generated by Django 3.0.2 on 2020-01-20 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0011_task_done_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 1, 21), null=True, verbose_name='完了した日'),
        ),
    ]
