# Generated by Django 3.0.2 on 2020-02-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0012_auto_20200228_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='urgent',
            field=models.BooleanField(verbose_name='緊急'),
        ),
    ]
