# Generated by Django 3.0.2 on 2020-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0013_auto_20200229_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='period',
            field=models.IntegerField(default=0, verbose_name='時間帯'),
        ),
    ]
