# Generated by Django 3.0.2 on 2020-03-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0014_task_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='period',
            field=models.IntegerField(choices=[(0, '~12時'), (1, '12~15時'), (2, '15~18時'), (3, '18~21時'), (4, '21~24時')], default=0, verbose_name='時間帯'),
        ),
    ]
