# Generated by Django 3.0.2 on 2020-03-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0016_auto_20200316_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='period',
            field=models.CharField(choices=[('~12時', '~12時'), ('12~15時', '12~15時'), ('15~18時', '15~18時'), ('18~21時', '18~21時'), ('21時~', '21時~')], default='~12時', max_length=16, verbose_name='時間帯'),
        ),
    ]
