# Generated by Django 3.0.2 on 2020-03-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0018_auto_20200318_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expired',
            field=models.BooleanField(default=False, verbose_name='期限切れ'),
        ),
    ]
