# Generated by Django 3.0.2 on 2020-04-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0019_task_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False, verbose_name='重要'),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='緊急'),
        ),
    ]
