# Generated by Django 3.0.2 on 2020-08-18 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0020_auto_20200425_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='期限'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='完了した日'),
        ),
        migrations.AlterField(
            model_name='task',
            name='when',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='実行予定日'),
        ),
    ]
