# Generated by Django 3.0.2 on 2020-06-24 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0022_auto_20200625_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='完了した日'),
        ),
    ]
