# Generated by Django 3.1.2 on 2020-10-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='order',
            field=models.IntegerField(default=0, verbose_name='順番'),
        ),
    ]
