# Generated by Django 3.1.2 on 2020-10-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_routine_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='order',
        ),
        migrations.AlterField(
            model_name='routine',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='ルーティン名'),
        ),
    ]
