# Generated by Django 3.1.2 on 2020-10-23 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_auto_20201023_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='days',
            field=models.IntegerField(choices=[(0, '毎日'), (1, '平日'), (2, '週末'), (3, '月'), (4, '火'), (5, '水'), (6, '木'), (7, '金'), (8, '土'), (9, '日')], default=0, verbose_name='曜日タイプ'),
        ),
        migrations.CreateModel(
            name='AddRoutine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visited', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
