# Generated by Django 3.1.2 on 2020-10-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20201023_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='addroutine',
            name='add_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
