# Generated by Django 3.1.2 on 2021-04-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_addroutine_add_or_not'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='important',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='urgent',
        ),
        migrations.AddField(
            model_name='routine',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='予定'),
        ),
        migrations.AddField(
            model_name='routine',
            name='time',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=3, null=True, verbose_name='所要時間'),
        ),
    ]
