# Generated by Django 3.0.2 on 2020-04-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('小説', '小説'), ('アカデミック', 'アカデミック'), ('テクノロジー', 'テクノロジー'), ('ビジネス', 'ビジネス'), ('自己啓発', '自己啓発')], default='小説', max_length=32, verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=128, verbose_name='タイトル'),
        ),
    ]
