# Generated by Django 3.0.2 on 2020-03-06 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(default='test', max_length=255, verbose_name='テスト')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='機能名')),
                ('description', models.TextField(blank=True, default='', verbose_name='機能追加の説明')),
                ('updated_at', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='追加日')),
            ],
        ),
    ]
