# Generated by Django 3.0.2 on 2020-03-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='updated_or_not',
            field=models.BooleanField(default=False, verbose_name='更新済み'),
        ),
    ]
