# Generated by Django 3.0.2 on 2020-04-04 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_update_updated_or_not'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='機能追加の説明'),
        ),
        migrations.AlterField(
            model_name='update',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='機能名'),
        ),
        migrations.AlterField(
            model_name='update',
            name='updated_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='追加日'),
        ),
    ]
