# Generated by Django 3.0.2 on 2020-04-04 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_auto_20200404_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='updated_or_not',
        ),
    ]
